<?php
/**
 * Favorite view.
 *
 * Rendered by Kind_View::get_view_part(). To change it, copy this file into a
 * kind_views folder in your theme; see develop.txt.
 *
 * @package Post_Kinds
 * @since   2.6.1
 *
 * @var Kind_Post    $kind_post The post being displayed.
 * @var string       $kind      The kind's slug, such as 'like'.
 * @var string       $type      The kind's microformats property, such as 'like-of'.
 * @var array        $cite      The citation, normalized by Kind_Post::normalize_cite(),
 *                              so every key is present. 'name' falls back to the URL.
 * @var string       $url       The cited URL.
 * @var string|false $author    The cited authors as h-card markup, listed as in "Ann, Bob and Cat", or false if there are none.
 * @var string       $embed     Embed markup for the cited URL, or an empty string.
 * @var int[]|false  $photos    Attachment IDs of the post's photos, from Kind_Post::get_photo().
 * @var array        $args      Arguments passed to Kind_View::get_view_part(); 'post_id' is the post's ID.
 */

defined( 'ABSPATH' ) || exit;

if ( ! $cite ) {
	return;
}

?>

<section class="response u-favorite-of h-cite">
<header>
<?php
echo Kind_Taxonomy::get_before_kind( 'favorite' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- get_before_kind() escapes the kind name; the icon is the plugin's own SVG.
if ( ! $embed ) {
	echo Kind_View::get_cite_title( $cite ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Kind_View::get_cite_title() escapes its output.
	if ( $author ) {
		echo ' ' . esc_html__( 'by', 'indieweb-post-kinds' ) . ' ' . $author; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- h-cards from Kind_View::get_hcard(), which escapes them.
	}
	$site_name = Kind_View::get_site_name( $cite );
	if ( $site_name ) {
		echo ' <em>(' . $site_name . ')</em>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Kind_View::get_site_name() escapes its output.
	}
}
?>
</header>
<?php
if ( $cite ) {
	if ( $embed ) {
		printf( '<blockquote class="e-summary">%1$s</blockquote>', $embed ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- oEmbed or media markup generated by WordPress core.
	} else {
		echo Kind_View::get_summary( $cite ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Kind_View::get_summary() escapes its output.
	}
}

// Close Response.
?>
</section>

<?php
