name: ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Detect coding standard violations
        run: npm run lint:js
