name: 'WordPress Plugin Check'
on: # rebuild any PRs and trunk branch changes
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        exclude-directories: |
          './bin'
          './.github'
          './lib/parse-this'
        exclude-checks: 'file_type'
